// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v4.0.30319.1
//

namespace AdvantShop.Payment.AlfabankSoap
{
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name = "orderv2", Namespace = "http://www.sirena-travel.ru")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public class AlfabankService2 : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback cancelOperationCompleted;

        private System.Threading.SendOrPostCallback confirmOperationCompleted;

        private System.Threading.SendOrPostCallback get_finishedOperationCompleted;

        private System.Threading.SendOrPostCallback get_statusOperationCompleted;

        private System.Threading.SendOrPostCallback refundOperationCompleted;

        private System.Threading.SendOrPostCallback register_agencyOperationCompleted;

        private System.Threading.SendOrPostCallback register_offlineOperationCompleted;

        private System.Threading.SendOrPostCallback register_onlineOperationCompleted;

        private System.Threading.SendOrPostCallback rejectOperationCompleted;

        private bool Validator(object Sender, System.Security.Cryptography.X509Certificates.X509Certificate Cert,
              System.Security.Cryptography.X509Certificates.X509Chain Chain, System.Net.Security.SslPolicyErrors Policy)
        {
            return true;
        }

        public AlfabankService2(string userName, string password, bool isSandBox)
        {
            System.Net.ServicePointManager.ServerCertificateValidationCallback = Validator;
            Url = isSandBox ? "https://tws.egopay.ru/order/v2/" : "https://tws.egopay.ru/order/v2/";
            Credentials = new System.Net.NetworkCredential(userName, password);
        }

        public event cancelCompletedEventHandler cancelCompleted;

        public event confirmCompletedEventHandler confirmCompleted;

        public event get_finishedCompletedEventHandler get_finishedCompleted;

        public event get_statusCompletedEventHandler get_statusCompleted;

        public event refundCompletedEventHandler refundCompleted;

        public event register_agencyCompletedEventHandler register_agencyCompleted;

        public event register_offlineCompletedEventHandler register_offlineCompleted;

        public event register_onlineCompletedEventHandler register_onlineCompleted;

        public event rejectCompletedEventHandler rejectCompleted;

        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("cancel", ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare, Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("cancelResponse", Namespace = "http://www.sirena-travel.ru")]
        public cancelResponse cancel([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.sirena-travel.ru")] cancel cancel)
        {
            object[] results = this.Invoke("cancel", new object[] {
                    cancel});
            return ((cancelResponse)(results[0]));
        }

        public System.IAsyncResult Begincancel(cancel cancel, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("cancel", new object[] {
                    cancel}, callback, asyncState);
        }

        public cancelResponse Endcancel(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((cancelResponse)(results[0]));
        }

        public void cancelAsync(cancel cancel)
        {
            this.cancelAsync(cancel, null);
        }

        public void cancelAsync(cancel cancel, object userState)
        {
            if ((this.cancelOperationCompleted == null))
            {
                this.cancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelCompleted);
            }
            this.InvokeAsync("cancel", new object[] {
                    cancel}, this.cancelOperationCompleted, userState);
        }

        private void OncancelCompleted(object arg)
        {
            if ((this.cancelCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelCompleted(this, new cancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("confirm", ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare, Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("confirmResponse", Namespace = "http://www.sirena-travel.ru")]
        public confirmResponse confirm([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.sirena-travel.ru")] confirm confirm)
        {
            object[] results = this.Invoke("confirm", new object[] {
                    confirm});
            return ((confirmResponse)(results[0]));
        }

        public System.IAsyncResult Beginconfirm(confirm confirm, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("confirm", new object[] {
                    confirm}, callback, asyncState);
        }

        public confirmResponse Endconfirm(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((confirmResponse)(results[0]));
        }

        public void confirmAsync(confirm confirm)
        {
            this.confirmAsync(confirm, null);
        }

        public void confirmAsync(confirm confirm, object userState)
        {
            if ((this.confirmOperationCompleted == null))
            {
                this.confirmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmCompleted);
            }
            this.InvokeAsync("confirm", new object[] {
                    confirm}, this.confirmOperationCompleted, userState);
        }

        private void OnconfirmCompleted(object arg)
        {
            if ((this.confirmCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.confirmCompleted(this, new confirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("get_finished", ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare, Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("get_finishedResponse", Namespace = "http://www.sirena-travel.ru")]
        public get_finishedResponse get_finished([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.sirena-travel.ru")] get_finished get_finished)
        {
            object[] results = this.Invoke("get_finished", new object[] {
                    get_finished});
            return ((get_finishedResponse)(results[0]));
        }

        public System.IAsyncResult Beginget_finished(get_finished get_finished, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_finished", new object[] {
                    get_finished}, callback, asyncState);
        }

        public get_finishedResponse Endget_finished(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((get_finishedResponse)(results[0]));
        }

        public void get_finishedAsync(get_finished get_finished)
        {
            this.get_finishedAsync(get_finished, null);
        }

        public void get_finishedAsync(get_finished get_finished, object userState)
        {
            if ((this.get_finishedOperationCompleted == null))
            {
                this.get_finishedOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_finishedCompleted);
            }
            this.InvokeAsync("get_finished", new object[] {
                    get_finished}, this.get_finishedOperationCompleted, userState);
        }

        private void Onget_finishedCompleted(object arg)
        {
            if ((this.get_finishedCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_finishedCompleted(this, new get_finishedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("get_status", ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare, Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("get_statusResponse", Namespace = "http://www.sirena-travel.ru")]
        public get_statusResponse get_status([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.sirena-travel.ru")] get_status get_status)
        {
            object[] results = this.Invoke("get_status", new object[] {
                    get_status});
            return ((get_statusResponse)(results[0]));
        }

        public System.IAsyncResult Beginget_status(get_status get_status, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_status", new object[] {
                    get_status}, callback, asyncState);
        }

        public get_statusResponse Endget_status(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((get_statusResponse)(results[0]));
        }

        public void get_statusAsync(get_status get_status)
        {
            this.get_statusAsync(get_status, null);
        }

        public void get_statusAsync(get_status get_status, object userState)
        {
            if ((this.get_statusOperationCompleted == null))
            {
                this.get_statusOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_statusCompleted);
            }
            this.InvokeAsync("get_status", new object[] {
                    get_status}, this.get_statusOperationCompleted, userState);
        }

        private void Onget_statusCompleted(object arg)
        {
            if ((this.get_statusCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_statusCompleted(this, new get_statusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("refund", ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare, Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("refundResponse", Namespace = "http://www.sirena-travel.ru")]
        public refundResponse refund([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.sirena-travel.ru")] refund refund)
        {
            object[] results = this.Invoke("refund", new object[] {
                    refund});
            return ((refundResponse)(results[0]));
        }

        public System.IAsyncResult Beginrefund(refund refund, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("refund", new object[] {
                    refund}, callback, asyncState);
        }

        public refundResponse Endrefund(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((refundResponse)(results[0]));
        }

        public void refundAsync(refund refund)
        {
            this.refundAsync(refund, null);
        }

        public void refundAsync(refund refund, object userState)
        {
            if ((this.refundOperationCompleted == null))
            {
                this.refundOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrefundCompleted);
            }
            this.InvokeAsync("refund", new object[] {
                    refund}, this.refundOperationCompleted, userState);
        }

        private void OnrefundCompleted(object arg)
        {
            if ((this.refundCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.refundCompleted(this, new refundCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("register_agency", ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare, Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("register_agencyResponse", Namespace = "http://www.sirena-travel.ru")]
        public register_agencyResponse register_agency([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.sirena-travel.ru")] register_agency register_agency)
        {
            object[] results = this.Invoke("register_agency", new object[] {
                    register_agency});
            return ((register_agencyResponse)(results[0]));
        }

        public System.IAsyncResult Beginregister_agency(register_agency register_agency, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("register_agency", new object[] {
                    register_agency}, callback, asyncState);
        }

        public register_agencyResponse Endregister_agency(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((register_agencyResponse)(results[0]));
        }

        public void register_agencyAsync(register_agency register_agency)
        {
            this.register_agencyAsync(register_agency, null);
        }

        public void register_agencyAsync(register_agency register_agency, object userState)
        {
            if ((this.register_agencyOperationCompleted == null))
            {
                this.register_agencyOperationCompleted = new System.Threading.SendOrPostCallback(this.Onregister_agencyCompleted);
            }
            this.InvokeAsync("register_agency", new object[] {
                    register_agency}, this.register_agencyOperationCompleted, userState);
        }

        private void Onregister_agencyCompleted(object arg)
        {
            if ((this.register_agencyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.register_agencyCompleted(this, new register_agencyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("register_offline", ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare, Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("register_offlineResponse", Namespace = "http://www.sirena-travel.ru")]
        public register_offlineResponse register_offline([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.sirena-travel.ru")] register_offline register_offline)
        {
            object[] results = this.Invoke("register_offline", new object[] {
                    register_offline});
            return ((register_offlineResponse)(results[0]));
        }

        public System.IAsyncResult Beginregister_offline(register_offline register_offline, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("register_offline", new object[] {
                    register_offline}, callback, asyncState);
        }

        public register_offlineResponse Endregister_offline(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((register_offlineResponse)(results[0]));
        }

        public void register_offlineAsync(register_offline register_offline)
        {
            this.register_offlineAsync(register_offline, null);
        }

        public void register_offlineAsync(register_offline register_offline, object userState)
        {
            if ((this.register_offlineOperationCompleted == null))
            {
                this.register_offlineOperationCompleted = new System.Threading.SendOrPostCallback(this.Onregister_offlineCompleted);
            }
            this.InvokeAsync("register_offline", new object[] {
                    register_offline}, this.register_offlineOperationCompleted, userState);
        }

        private void Onregister_offlineCompleted(object arg)
        {
            if ((this.register_offlineCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.register_offlineCompleted(this, new register_offlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("register_online", ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare, Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("register_onlineResponse", Namespace = "http://www.sirena-travel.ru")]
        public register_onlineResponse register_online([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.sirena-travel.ru")] register_online register_online)
        {
            object[] results = this.Invoke("register_online", new object[] {
                    register_online});
            return ((register_onlineResponse)(results[0]));
        }

        public System.IAsyncResult Beginregister_online(register_online register_online, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("register_online", new object[] {
                    register_online}, callback, asyncState);
        }

        public register_onlineResponse Endregister_online(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((register_onlineResponse)(results[0]));
        }

        public void register_onlineAsync(register_online register_online)
        {
            this.register_onlineAsync(register_online, null);
        }

        public void register_onlineAsync(register_online register_online, object userState)
        {
            if ((this.register_onlineOperationCompleted == null))
            {
                this.register_onlineOperationCompleted = new System.Threading.SendOrPostCallback(this.Onregister_onlineCompleted);
            }
            this.InvokeAsync("register_online", new object[] {
                    register_online}, this.register_onlineOperationCompleted, userState);
        }

        private void Onregister_onlineCompleted(object arg)
        {
            if ((this.register_onlineCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.register_onlineCompleted(this, new register_onlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("reject", ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare, Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("rejectResponse", Namespace = "http://www.sirena-travel.ru")]
        public rejectResponse reject([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.sirena-travel.ru")] reject reject)
        {
            object[] results = this.Invoke("reject", new object[] {
                    reject});
            return ((rejectResponse)(results[0]));
        }

        public System.IAsyncResult Beginreject(reject reject, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("reject", new object[] {
                    reject}, callback, asyncState);
        }

        public rejectResponse Endreject(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((rejectResponse)(results[0]));
        }

        public void rejectAsync(reject reject)
        {
            this.rejectAsync(reject, null);
        }

        public void rejectAsync(reject reject, object userState)
        {
            if ((this.rejectOperationCompleted == null))
            {
                this.rejectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrejectCompleted);
            }
            this.InvokeAsync("reject", new object[] {
                    reject}, this.rejectOperationCompleted, userState);
        }

        private void OnrejectCompleted(object arg)
        {
            if ((this.rejectCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rejectCompleted(this, new rejectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class cancel
    {

        private OrderID orderField;

        /// <remarks/>
        public OrderID order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class OrderID
    {

        private System.Nullable<int> shop_idField;

        private string numberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, DataType = "int")]
        public System.Nullable<int> shop_id
        {
            get
            {
                return this.shop_idField;
            }
            set
            {
                this.shop_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class cancelResponse
    {

        private OrderStatus retvalField;

        /// <remarks/>
        public OrderStatus retval
        {
            get
            {
                return this.retvalField;
            }
            set
            {
                this.retvalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class OrderStatus
    {

        private string statusField;

        private OrderID orderField1;

        private string shoprefField;

        private Payment[] paymentsField;

        private Error errorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public OrderID order
        {
            get
            {
                return this.orderField1;
            }
            set
            {
                this.orderField1 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string shopref
        {
            get
            {
                return this.shoprefField;
            }
            set
            {
                this.shoprefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable = false)]
        public Payment[] payments
        {
            get
            {
                return this.paymentsField;
            }
            set
            {
                this.paymentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Error error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class Payment
    {

        private string authorgField;

        private string authcodeField;

        private string salepointField;

        private string clearingField;

        private Amount amountField;

        private Document docField;

        private System.Nullable<System.DateTime> dateField;

        private string typeField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string authorg
        {
            get
            {
                return this.authorgField;
            }
            set
            {
                this.authorgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string authcode
        {
            get
            {
                return this.authcodeField;
            }
            set
            {
                this.authcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string salepoint
        {
            get
            {
                return this.salepointField;
            }
            set
            {
                this.salepointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string clearing
        {
            get
            {
                return this.clearingField;
            }
            set
            {
                this.clearingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Amount amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Document doc
        {
            get
            {
                return this.docField;
            }
            set
            {
                this.docField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, DataType = "dateTime")]
        public System.Nullable<System.DateTime> date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class Amount
    {

        private string currencyField;

        private System.Nullable<float> amountField1;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, DataType = "float")]
        public System.Nullable<float> amount
        {
            get
            {
                return this.amountField1;
            }
            set
            {
                this.amountField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class Document
    {

        private string codeField;

        private string holderField;

        private string numberField1;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string holder
        {
            get
            {
                return this.holderField;
            }
            set
            {
                this.holderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string number
        {
            get
            {
                return this.numberField1;
            }
            set
            {
                this.numberField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class Error
    {

        private string categoryField;

        private string codeField1;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string code
        {
            get
            {
                return this.codeField1;
            }
            set
            {
                this.codeField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class confirm
    {

        private OrderID orderField2;

        private OrderTicket[] ticketsField;

        /// <remarks/>
        public OrderID order
        {
            get
            {
                return this.orderField2;
            }
            set
            {
                this.orderField2 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable = false)]
        public OrderTicket[] tickets
        {
            get
            {
                return this.ticketsField;
            }
            set
            {
                this.ticketsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class OrderTicket
    {

        private string[] ticketsField1;

        private string typenameField;

        private string hostField;

        private string numberField2;

        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable = false)]
        public string[] tickets
        {
            get
            {
                return this.ticketsField1;
            }
            set
            {
                this.ticketsField1 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string typename
        {
            get
            {
                return this.typenameField;
            }
            set
            {
                this.typenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string host
        {
            get
            {
                return this.hostField;
            }
            set
            {
                this.hostField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string number
        {
            get
            {
                return this.numberField2;
            }
            set
            {
                this.numberField2 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class confirmResponse
    {

        private OrderStatus retvalField1;

        /// <remarks/>
        public OrderStatus retval
        {
            get
            {
                return this.retvalField1;
            }
            set
            {
                this.retvalField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class get_finished
    {

        private int shop_idField1;

        private System.DateTime startField;

        private System.DateTime stopField;

        /// <remarks/>
        public int shop_id
        {
            get
            {
                return this.shop_idField1;
            }
            set
            {
                this.shop_idField1 = value;
            }
        }

        /// <remarks/>
        public System.DateTime start
        {
            get
            {
                return this.startField;
            }
            set
            {
                this.startField = value;
            }
        }

        /// <remarks/>
        public System.DateTime stop
        {
            get
            {
                return this.stopField;
            }
            set
            {
                this.stopField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class get_finishedResponse
    {

        private OrderStatus[] retvalField2;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable = false)]
        public OrderStatus[] retval
        {
            get
            {
                return this.retvalField2;
            }
            set
            {
                this.retvalField2 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class get_status
    {

        private OrderID orderField3;

        /// <remarks/>
        public OrderID order
        {
            get
            {
                return this.orderField3;
            }
            set
            {
                this.orderField3 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class get_statusResponse
    {

        private OrderStatus retvalField3;

        /// <remarks/>
        public OrderStatus retval
        {
            get
            {
                return this.retvalField3;
            }
            set
            {
                this.retvalField3 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class refund
    {

        private OrderID orderField4;

        private string payment_idField;

        private Amount costField;

        private string refund_idField;

        /// <remarks/>
        public OrderID order
        {
            get
            {
                return this.orderField4;
            }
            set
            {
                this.orderField4 = value;
            }
        }

        /// <remarks/>
        public string payment_id
        {
            get
            {
                return this.payment_idField;
            }
            set
            {
                this.payment_idField = value;
            }
        }

        /// <remarks/>
        public Amount cost
        {
            get
            {
                return this.costField;
            }
            set
            {
                this.costField = value;
            }
        }

        /// <remarks/>
        public string refund_id
        {
            get
            {
                return this.refund_idField;
            }
            set
            {
                this.refund_idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class refundResponse
    {

        private OrderStatus retvalField4;

        /// <remarks/>
        public OrderStatus retval
        {
            get
            {
                return this.retvalField4;
            }
            set
            {
                this.retvalField4 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class register_agency
    {

        private OrderID orderField5;

        private Amount costField1;

        private CustomerInfo customerField;

        private OrderInfo descriptionField;

        private DepositInfo accountField;

        private PostEntry[] postdataField;

        /// <remarks/>
        public OrderID order
        {
            get
            {
                return this.orderField5;
            }
            set
            {
                this.orderField5 = value;
            }
        }

        /// <remarks/>
        public Amount cost
        {
            get
            {
                return this.costField1;
            }
            set
            {
                this.costField1 = value;
            }
        }

        /// <remarks/>
        public CustomerInfo customer
        {
            get
            {
                return this.customerField;
            }
            set
            {
                this.customerField = value;
            }
        }

        /// <remarks/>
        public OrderInfo description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public DepositInfo account
        {
            get
            {
                return this.accountField;
            }
            set
            {
                this.accountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable = false)]
        public PostEntry[] postdata
        {
            get
            {
                return this.postdataField;
            }
            set
            {
                this.postdataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class CustomerInfo
    {

        private string idField1;

        private string phoneField;

        private string nameField;

        private string emailField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string id
        {
            get
            {
                return this.idField1;
            }
            set
            {
                this.idField1 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class OrderInfo
    {

        private OrderItem[] itemsField;

        private string shoprefField1;

        private string paytypeField;

        private string descrField1;

        private System.Nullable<System.DateTime> timelimitField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable = false)]
        public OrderItem[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string shopref
        {
            get
            {
                return this.shoprefField1;
            }
            set
            {
                this.shoprefField1 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string paytype
        {
            get
            {
                return this.paytypeField;
            }
            set
            {
                this.paytypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string descr
        {
            get
            {
                return this.descrField1;
            }
            set
            {
                this.descrField1 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, DataType = "dateTime")]
        public System.Nullable<System.DateTime> timelimit
        {
            get
            {
                return this.timelimitField;
            }
            set
            {
                this.timelimitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class OrderItem
    {

        private string descrField;

        private string clearingField1;

        private Amount amountField2;

        private string numberField3;

        private string typenameField1;

        private string hostField1;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string descr
        {
            get
            {
                return this.descrField;
            }
            set
            {
                this.descrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string clearing
        {
            get
            {
                return this.clearingField1;
            }
            set
            {
                this.clearingField1 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Amount amount
        {
            get
            {
                return this.amountField2;
            }
            set
            {
                this.amountField2 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string number
        {
            get
            {
                return this.numberField3;
            }
            set
            {
                this.numberField3 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string typename
        {
            get
            {
                return this.typenameField1;
            }
            set
            {
                this.typenameField1 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string host
        {
            get
            {
                return this.hostField1;
            }
            set
            {
                this.hostField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class DepositInfo
    {

        private string salepointField1;

        private string remarkField;

        private string agreementField;

        private string userField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string salepoint
        {
            get
            {
                return this.salepointField1;
            }
            set
            {
                this.salepointField1 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string agreement
        {
            get
            {
                return this.agreementField;
            }
            set
            {
                this.agreementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class PostEntry
    {

        private string nameField1;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string name
        {
            get
            {
                return this.nameField1;
            }
            set
            {
                this.nameField1 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class register_agencyResponse
    {

        private OnlineResult retvalField5;

        /// <remarks/>
        public OnlineResult retval
        {
            get
            {
                return this.retvalField5;
            }
            set
            {
                this.retvalField5 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class OnlineResult
    {

        private string sessionField;

        private string redirect_urlField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string redirect_url
        {
            get
            {
                return this.redirect_urlField;
            }
            set
            {
                this.redirect_urlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class register_offline
    {

        private OrderID orderField6;

        private Amount costField2;

        private CustomerInfo customerField1;

        private OrderInfo descriptionField1;

        /// <remarks/>
        public OrderID order
        {
            get
            {
                return this.orderField6;
            }
            set
            {
                this.orderField6 = value;
            }
        }

        /// <remarks/>
        public Amount cost
        {
            get
            {
                return this.costField2;
            }
            set
            {
                this.costField2 = value;
            }
        }

        /// <remarks/>
        public CustomerInfo customer
        {
            get
            {
                return this.customerField1;
            }
            set
            {
                this.customerField1 = value;
            }
        }

        /// <remarks/>
        public OrderInfo description
        {
            get
            {
                return this.descriptionField1;
            }
            set
            {
                this.descriptionField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class register_offlineResponse
    {

        private OfflineResult retvalField6;

        /// <remarks/>
        public OfflineResult retval
        {
            get
            {
                return this.retvalField6;
            }
            set
            {
                this.retvalField6 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class OfflineResult
    {

        private string[] orgsField;

        private string paycodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable = false)]
        public string[] orgs
        {
            get
            {
                return this.orgsField;
            }
            set
            {
                this.orgsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string paycode
        {
            get
            {
                return this.paycodeField;
            }
            set
            {
                this.paycodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class register_online
    {

        private OrderID orderField7;

        private Amount costField3;

        private CustomerInfo customerField2;

        private OrderInfo descriptionField2;

        private PostEntry[] postdataField1;

        /// <remarks/>
        public OrderID order
        {
            get
            {
                return this.orderField7;
            }
            set
            {
                this.orderField7 = value;
            }
        }

        /// <remarks/>
        public Amount cost
        {
            get
            {
                return this.costField3;
            }
            set
            {
                this.costField3 = value;
            }
        }

        /// <remarks/>
        public CustomerInfo customer
        {
            get
            {
                return this.customerField2;
            }
            set
            {
                this.customerField2 = value;
            }
        }

        /// <remarks/>
        public OrderInfo description
        {
            get
            {
                return this.descriptionField2;
            }
            set
            {
                this.descriptionField2 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable = false)]
        public PostEntry[] postdata
        {
            get
            {
                return this.postdataField1;
            }
            set
            {
                this.postdataField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class register_onlineResponse
    {

        private OnlineResult retvalField7;

        /// <remarks/>
        public OnlineResult retval
        {
            get
            {
                return this.retvalField7;
            }
            set
            {
                this.retvalField7 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class reject
    {

        private OrderID orderField8;

        private string payment_idField1;

        /// <remarks/>
        public OrderID order
        {
            get
            {
                return this.orderField8;
            }
            set
            {
                this.orderField8 = value;
            }
        }

        /// <remarks/>
        public string payment_id
        {
            get
            {
                return this.payment_idField1;
            }
            set
            {
                this.payment_idField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sirena-travel.ru")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sirena-travel.ru")]
    public partial class rejectResponse
    {

        private OrderStatus retvalField8;

        /// <remarks/>
        public OrderStatus retval
        {
            get
            {
                return this.retvalField8;
            }
            set
            {
                this.retvalField8 = value;
            }
        }
    }

    public partial class cancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal cancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public cancelResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((cancelResponse)(this.results[0]));
            }
        }
    }

    public delegate void cancelCompletedEventHandler(object sender, cancelCompletedEventArgs args);

    public partial class confirmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal confirmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public confirmResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((confirmResponse)(this.results[0]));
            }
        }
    }

    public delegate void confirmCompletedEventHandler(object sender, confirmCompletedEventArgs args);

    public partial class get_finishedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal get_finishedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public get_finishedResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((get_finishedResponse)(this.results[0]));
            }
        }
    }

    public delegate void get_finishedCompletedEventHandler(object sender, get_finishedCompletedEventArgs args);

    public partial class get_statusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal get_statusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public get_statusResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((get_statusResponse)(this.results[0]));
            }
        }
    }

    public delegate void get_statusCompletedEventHandler(object sender, get_statusCompletedEventArgs args);

    public partial class refundCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal refundCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public refundResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((refundResponse)(this.results[0]));
            }
        }
    }

    public delegate void refundCompletedEventHandler(object sender, refundCompletedEventArgs args);

    public partial class register_agencyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal register_agencyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public register_agencyResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((register_agencyResponse)(this.results[0]));
            }
        }
    }

    public delegate void register_agencyCompletedEventHandler(object sender, register_agencyCompletedEventArgs args);

    public partial class register_offlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal register_offlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public register_offlineResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((register_offlineResponse)(this.results[0]));
            }
        }
    }

    public delegate void register_offlineCompletedEventHandler(object sender, register_offlineCompletedEventArgs args);

    public partial class register_onlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal register_onlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public register_onlineResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((register_onlineResponse)(this.results[0]));
            }
        }
    }

    public delegate void register_onlineCompletedEventHandler(object sender, register_onlineCompletedEventArgs args);

    public partial class rejectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal rejectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public rejectResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((rejectResponse)(this.results[0]));
            }
        }
    }

    public delegate void rejectCompletedEventHandler(object sender, rejectCompletedEventArgs args);
}
